name: TypeGood
options:
  bundleIdPrefix: com.typegood
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
    ENABLE_HARDENED_RUNTIME: true
    CODE_SIGN_IDENTITY: "TypeGood Developer"
    PRODUCT_BUNDLE_IDENTIFIER: com.typegood.app

targets:
  TypeGood:
    type: application
    platform: macOS
    sources:
      - TypeGood
    settings:
      base:
        INFOPLIST_FILE: TypeGood/Resources/Info.plist
        PRODUCT_NAME: TypeGood
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        COMBINE_HIDPI_IMAGES: true
        LD_RUNPATH_SEARCH_PATHS: "$(inherited) @executable_path/../Frameworks"
        ENABLE_APP_SANDBOX: false
        CODE_SIGN_ENTITLEMENTS: TypeGood/Resources/TypeGood.entitlements
    entitlements:
      path: TypeGood/Resources/TypeGood.entitlements
      properties:
        com.apple.security.device.audio-input: true
